In [2]:
import numpy as np
import pandas as pd
from numpy import nan as NA
import geopy
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="geoapiExercises")

In [56]:
df = pd.read_csv('/Users/jennyjang/Desktop/CS Project/datasets/full.csv')

/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (13) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [28]:
df

,Unnamed: 0,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,...,rideable_type,start_lat,start_lng,end_lat,end_lng,id,temp_start_lat,temp_start_lng,temp_end_lat,temp_end_lng
0,0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,...,NaN,NaN,NaN,NaN,NaN,1,38.912097,-77.038689,38.912097,-77.038689
1,1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,...,NaN,NaN,NaN,NaN,NaN,2,38.887374,-77.001958,38.887374,-77.001958
2,2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,...,NaN,NaN,NaN,NaN,NaN,3,38.912097,-77.038689,38.912097,-77.038689
3,3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,...,NaN,NaN,NaN,NaN,NaN,4,38.938741,-77.087181,38.938741,-77.087181
4,4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,...,NaN,NaN,NaN,NaN,NaN,5,38.908644,-77.012366,38.908644,-77.012366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,158125,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,...,NaN,NaN,NaN,NaN,NaN,158126,38.905731,-77.022264,38.905731,-77.022264
5737814,158126,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,...,NaN,NaN,NaN,NaN,NaN,158127,38.908596,-77.032308,38.908596,-77.032308
5737815,158127,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,...,NaN,NaN,NaN,NaN,NaN,158128,38.917807,-77.032079,38.917807,-77.032079
5737816,158128,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,...,NaN,NaN,NaN,NaN,NaN,158129,38.884090,-76.995180,38.884090,-76.995180
5737817,158129,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,...,NaN,NaN,NaN,NaN,NaN,158130,38.906599,-77.051494,38.906599,-77.051494

In [57]:
for col in df.columns:
    print(col)

Unnamed: 0
Duration
started_at
ended_at
start_station_id
start_station_name
end_station_id
end_station_name
ride_id
member_casual
fileid
year
month
rideable_type
start_lat
start_lng
end_lat
end_lng
id
temp_start_lat
temp_start_lng
temp_end_lat
temp_end_lng

In [58]:
df = df.drop(columns=['Unnamed: 0','month','year','start_lat','start_lng','end_lat','end_lng'])

hello world

In [59]:
df

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,rideable_type,id,temp_start_lat,temp_start_lng,temp_end_lat,temp_end_lng
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,NaN,1,38.912097,-77.038689,38.912097,-77.038689
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,NaN,2,38.887374,-77.001958,38.887374,-77.001958
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,NaN,3,38.912097,-77.038689,38.912097,-77.038689
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,NaN,4,38.938741,-77.087181,38.938741,-77.087181
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,NaN,5,38.908644,-77.012366,38.908644,-77.012366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,NaN,158126,38.905731,-77.022264,38.905731,-77.022264
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,NaN,158127,38.908596,-77.032308,38.908596,-77.032308
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,NaN,158128,38.917807,-77.032079,38.917807,-77.032079
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,NaN,158129,38.884090,-76.995180,38.884090,-76.995180
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,NaN,158130,38.906599,-77.051494,38.906599,-77.051494

In [60]:
# renaming the new columns
df2 = df.rename(columns = {'temp_start_lat': 'new_start_lat', 'temp_start_lng': 'new_start_lng', 'temp_end_lat':'new_end_lat', 'temp_end_lng':'new_end_lng' }, inplace = False)
df2

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,rideable_type,id,new_start_lat,new_start_lng,new_end_lat,new_end_lng
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,NaN,1,38.912097,-77.038689,38.912097,-77.038689
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,NaN,2,38.887374,-77.001958,38.887374,-77.001958
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,NaN,3,38.912097,-77.038689,38.912097,-77.038689
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,NaN,4,38.938741,-77.087181,38.938741,-77.087181
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,NaN,5,38.908644,-77.012366,38.908644,-77.012366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,NaN,158126,38.905731,-77.022264,38.905731,-77.022264
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,NaN,158127,38.908596,-77.032308,38.908596,-77.032308
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,NaN,158128,38.917807,-77.032079,38.917807,-77.032079
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,NaN,158129,38.884090,-76.995180,38.884090,-76.995180
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,NaN,158130,38.906599,-77.051494,38.906599,-77.051494

In [53]:
# Trying to make the station id integer form.
# stationid=[]
# def strip0 (row):
#     stationid=str(row['start_station_id']).split('.')[0]
#     return stationid

# strip_apply = df2.apply(strip0, axis=1)

# not working properly for some reason

In [63]:
df2

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,rideable_type,id,new_start_lat,new_start_lng,new_end_lat,new_end_lng
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,NaN,1,38.912097,-77.038689,38.912097,-77.038689
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,NaN,2,38.887374,-77.001958,38.887374,-77.001958
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,NaN,3,38.912097,-77.038689,38.912097,-77.038689
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,NaN,4,38.938741,-77.087181,38.938741,-77.087181
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,NaN,5,38.908644,-77.012366,38.908644,-77.012366
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,NaN,158126,38.905731,-77.022264,38.905731,-77.022264
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,NaN,158127,38.908596,-77.032308,38.908596,-77.032308
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,NaN,158128,38.917807,-77.032079,38.917807,-77.032079
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,NaN,158129,38.884090,-76.995180,38.884090,-76.995180
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,NaN,158130,38.906599,-77.051494,38.906599,-77.051494

In [61]:
#df.to_csv(r'/Users/jennyjang/Desktop/CS Project/datasets/full_v2.csv')

Trying Geopy

In [69]:
temp = df2[["start_station_id","new_start_lat","new_start_lng"]]
temp = temp.groupby("start_station_id").mean()
temp= temp[temp['new_start_lat'].notnull()]
temp

                  new_start_lat  new_start_lng
start_station_id
31000.0               38.858972     -77.053234
31001.0               38.857250     -77.053355
31002.0               38.856422     -77.049237
31003.0               38.860282     -77.049568
31004.0               38.857866     -77.059490
...                         ...            ...
32607.0               38.879737     -77.178396
32608.0               38.885424     -77.173586
32609.0               38.885623     -77.166917
32900.0               38.964406     -77.010759
32901.0               38.963810     -77.010266

[633 rows x 2 columns]

In [71]:
startlatlst=temp['new_start_lat'].tolist()
startlnglst=temp['new_start_lng'].tolist()
newlst=[]
x=list((zip(startlatlst,startlnglst)))
for i in x:
  x0=round(i[0],6)
  x1=round(i[1],6)
  newpair=str(x0) + ","+str(x1)
  newlst.append(newpair)
newlst = list( dict.fromkeys(newlst))
print(len(newlst))

633

In [73]:
print(newlst[0:10])

['38.858972,-77.053234', '38.85725,-77.053355', '38.856422,-77.049237', '38.860282,-77.049568', '38.857866,-77.05949', '38.862287,-77.059938', '38.863667,-77.063308', '38.85741,-77.051134', '38.848451,-77.051481', '38.842602,-77.050204']

In [74]:
statels=[]
for i in newlst:
  try:
    location=(geolocator.reverse(i))
    address = location.raw['address']
    state = address.get('state', '')
    statels.append(state)
  except:
    print('error in',i)
    break
temp['state']=statels

In [123]:
# County Variable
#Start a log for error reporting

fileout=open("Exception_Log.txt",'a')

#Create County variable
countyls=[]
for i in newlst:
  try:
    location=(geolocator.reverse(i))
    address = location.raw['address']
    county = address.get('county', '')
    countyls.append(county)
  except:
    print('error in',i)
    fileout.write(i)
    break

temp['county']=countyls

In [125]:
#Create City variable
cityls=[]
for i in newlst:
  try:
    location=(geolocator.reverse(i))
    address = location.raw['address']
    city = address.get('city', '')
    cityls.append(city)
  except:
    print('error in',i)
    fileout.write(i)

    break
temp['city']=cityls

fileout.close()

In [126]:
#This section combines county and city to create a single 'locale' variable.
#https://www.codegrepper.com/code-examples/python/pandas+replace+column+values+with+another+column
temp['locale']=temp['county']
temp['locale'] = np.where(temp['locale'] == "", temp['city'], temp['locale'])

In [127]:
#temp=temp.reset_index()
temp

,index,start_station_id,new_start_lat,new_start_lng,state,county,city,locale
0,0,31000.0,38.858972,-77.053234,Virginia,Arlington County,Arlington,Arlington County
1,1,31001.0,38.857250,-77.053355,Virginia,Arlington County,Arlington,Arlington County
2,2,31002.0,38.856422,-77.049237,Virginia,Arlington County,Arlington,Arlington County
3,3,31003.0,38.860282,-77.049568,Virginia,Arlington County,Arlington,Arlington County
4,4,31004.0,38.857866,-77.059490,Virginia,Arlington County,Arlington,Arlington County
...,...,...,...,...,...,...,...,...
628,628,32607.0,38.879737,-77.178396,Virginia,Fairfax (city),,Fairfax (city)
629,629,32608.0,38.885424,-77.173586,Virginia,Fairfax (city),Arlington,Fairfax (city)
630,630,32609.0,38.885623,-77.166917,Virginia,,,
631,631,32900.0,38.964406,-77.010759,District of Columbia,,Washington,Washington
632,632,32901.0,38.963810,-77.010266,District of Columbia,,Washington,Washington

In [128]:
# Now merging two df based on the station_id
df3 = pd.merge(left=df2, right=temp, how='left', left_on='start_station_id', right_on='start_station_id')

In [129]:
df3

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,...,new_start_lng_x,new_end_lat,new_end_lng,index,new_start_lat_y,new_start_lng_y,state,county,city,locale
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,...,-77.038689,38.912097,-77.038689,146.0,38.912097,-77.038689,District of Columbia,,Washington,Washington
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,...,-77.001958,38.887374,-77.001958,201.0,38.887374,-77.001958,District of Columbia,,Washington,Washington
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,...,-77.038689,38.912097,-77.038689,146.0,38.912097,-77.038689,District of Columbia,,Washington,Washington
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,...,-77.087181,38.938741,-77.087181,233.0,38.938741,-77.087181,District of Columbia,,Washington,Washington
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,...,-77.012366,38.908644,-77.012366,301.0,38.908644,-77.012366,District of Columbia,,Washington,Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,...,-77.022264,38.905731,-77.022264,155.0,38.905731,-77.022264,District of Columbia,,Washington,Washington
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,...,-77.032308,38.908596,-77.032308,136.0,38.908596,-77.032308,District of Columbia,,Washington,Washington
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,...,-77.032079,38.917807,-77.032079,100.0,38.917807,-77.032079,District of Columbia,,Washington,Washington
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,...,-76.995180,38.884090,-76.995180,326.0,38.884090,-76.995180,District of Columbia,,Washington,Washington
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,...,-77.051494,38.906599,-77.051494,187.0,38.906599,-77.051494,District of Columbia,,Washington,Washington

In [130]:
# Dropping overlapping columns
df3 = df3.drop(columns=['index','new_start_lat_y','new_start_lng_y'])

In [131]:
df3

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,rideable_type,id,new_start_lat_x,new_start_lng_x,new_end_lat,new_end_lng,state,county,city,locale
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,NaN,1,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,NaN,2,38.887374,-77.001958,38.887374,-77.001958,District of Columbia,,Washington,Washington
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,NaN,3,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,NaN,4,38.938741,-77.087181,38.938741,-77.087181,District of Columbia,,Washington,Washington
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,NaN,5,38.908644,-77.012366,38.908644,-77.012366,District of Columbia,,Washington,Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,NaN,158126,38.905731,-77.022264,38.905731,-77.022264,District of Columbia,,Washington,Washington
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,NaN,158127,38.908596,-77.032308,38.908596,-77.032308,District of Columbia,,Washington,Washington
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,NaN,158128,38.917807,-77.032079,38.917807,-77.032079,District of Columbia,,Washington,Washington
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,NaN,158129,38.884090,-76.995180,38.884090,-76.995180,District of Columbia,,Washington,Washington
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,NaN,158130,38.906599,-77.051494,38.906599,-77.051494,District of Columbia,,Washington,Washington

In [133]:
# renaiming new lat/long columns 
df3 = df3.rename(columns = {'new_start_lat_x': 'start_lat', 'new_start_lng_x': 'start_lng', 'temp_end_lat':'new_end_lat', 'new_end_lat':'end_lat', 'new_end_lng':'end_lng' }, inplace = False)
df3

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,rideable_type,id,start_lat,start_lng,end_lat,end_lng,state,county,city,locale
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,NaN,1,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,NaN,2,38.887374,-77.001958,38.887374,-77.001958,District of Columbia,,Washington,Washington
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,NaN,3,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,NaN,4,38.938741,-77.087181,38.938741,-77.087181,District of Columbia,,Washington,Washington
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,NaN,5,38.908644,-77.012366,38.908644,-77.012366,District of Columbia,,Washington,Washington
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,NaN,158126,38.905731,-77.022264,38.905731,-77.022264,District of Columbia,,Washington,Washington
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,NaN,158127,38.908596,-77.032308,38.908596,-77.032308,District of Columbia,,Washington,Washington
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,NaN,158128,38.917807,-77.032079,38.917807,-77.032079,District of Columbia,,Washington,Washington
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,NaN,158129,38.884090,-76.995180,38.884090,-76.995180,District of Columbia,,Washington,Washington
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,NaN,158130,38.906599,-77.051494,38.906599,-77.051494,District of Columbia,,Washington,Washington

In [135]:
#Extracting date to use in merge with Covid df
df3["started_at"] = pd.to_datetime(df3['started_at'])
df3['date'] = df3['started_at'].dt.date

In [136]:
df3

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,...,id,start_lat,start_lng,end_lat,end_lng,state,county,city,locale,date
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,...,1,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington,2019-10-01
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,...,2,38.887374,-77.001958,38.887374,-77.001958,District of Columbia,,Washington,Washington,2019-10-01
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,...,3,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington,2019-10-01
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,...,4,38.938741,-77.087181,38.938741,-77.087181,District of Columbia,,Washington,Washington,2019-10-01
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,...,5,38.908644,-77.012366,38.908644,-77.012366,District of Columbia,,Washington,Washington,2019-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,...,158126,38.905731,-77.022264,38.905731,-77.022264,District of Columbia,,Washington,Washington,2019-02-28
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,...,158127,38.908596,-77.032308,38.908596,-77.032308,District of Columbia,,Washington,Washington,2019-02-28
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,...,158128,38.917807,-77.032079,38.917807,-77.032079,District of Columbia,,Washington,Washington,2019-02-28
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,...,158129,38.884090,-76.995180,38.884090,-76.995180,District of Columbia,,Washington,Washington,2019-02-28
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,...,158130,38.906599,-77.051494,38.906599,-77.051494,District of Columbia,,Washington,Washington,2019-02-28

In [137]:
# Bringing in the covid data
covid = pd.read_csv("/Users/jennyjang/Desktop/CS Project/VDH-COVID-19-PublicUseDataset-Cases.csv")
covid

,Report Date,FIPS,Locality,VDH Health District,Total Cases,Hospitalizations,Deaths
0,11/28/2020,51001,Accomack,Eastern Shore,"1,340",107,21
1,11/28/2020,51003,Albemarle,Thomas Jefferson,"1,896",100,27
2,11/28/2020,51005,Alleghany,Alleghany,316,19,7
3,11/28/2020,51007,Amelia,Piedmont,210,21,6
4,11/28/2020,51009,Amherst,Central Virginia,810,31,6
...,...,...,...,...,...,...,...
51865,04/10/2021,51800,Suffolk,Western Tidewater,"7,568",426,180
51866,04/10/2021,51810,Virginia Beach,Virginia Beach,"33,960","1,483",369
51867,04/10/2021,51820,Waynesboro,Central Shenandoah,"2,280",71,35
51868,04/10/2021,51830,Williamsburg,Peninsula,727,24,11
51869,04/10/2021,51840,Winchester,Lord Fairfax,"2,726",109,41

In [138]:
covid['Report Date']= pd.to_datetime(covid['Report Date'])
covid

,Report Date,FIPS,Locality,VDH Health District,Total Cases,Hospitalizations,Deaths
0,2020-11-28,51001,Accomack,Eastern Shore,"1,340",107,21
1,2020-11-28,51003,Albemarle,Thomas Jefferson,"1,896",100,27
2,2020-11-28,51005,Alleghany,Alleghany,316,19,7
3,2020-11-28,51007,Amelia,Piedmont,210,21,6
4,2020-11-28,51009,Amherst,Central Virginia,810,31,6
...,...,...,...,...,...,...,...
51865,2021-04-10,51800,Suffolk,Western Tidewater,"7,568",426,180
51866,2021-04-10,51810,Virginia Beach,Virginia Beach,"33,960","1,483",369
51867,2021-04-10,51820,Waynesboro,Central Shenandoah,"2,280",71,35
51868,2021-04-10,51830,Williamsburg,Peninsula,727,24,11
51869,2021-04-10,51840,Winchester,Lord Fairfax,"2,726",109,41

In [139]:
## convert the numbers to int. Don't rerun this as it has beeen done already. ##
# covid['Total Cases'] =covid['Total Cases'].str.replace(',', '').astype(int)
# covid['Hospitalizations'] =covid['Hospitalizations'].str.replace(',', '').astype(int)
# covid['Deaths'] =covid['Deaths'].str.replace(',', '').astype(int)
covid

,Report Date,FIPS,Locality,VDH Health District,Total Cases,Hospitalizations,Deaths
0,2020-11-28,51001,Accomack,Eastern Shore,1340,107,21
1,2020-11-28,51003,Albemarle,Thomas Jefferson,1896,100,27
2,2020-11-28,51005,Alleghany,Alleghany,316,19,7
3,2020-11-28,51007,Amelia,Piedmont,210,21,6
4,2020-11-28,51009,Amherst,Central Virginia,810,31,6
...,...,...,...,...,...,...,...
51865,2021-04-10,51800,Suffolk,Western Tidewater,7568,426,180
51866,2021-04-10,51810,Virginia Beach,Virginia Beach,33960,1483,369
51867,2021-04-10,51820,Waynesboro,Central Shenandoah,2280,71,35
51868,2021-04-10,51830,Williamsburg,Peninsula,727,24,11
51869,2021-04-10,51840,Winchester,Lord Fairfax,2726,109,41

In [140]:
covid1 = covid[['Report Date','Total Cases','Hospitalizations','Deaths']]
covid

,Report Date,FIPS,Locality,VDH Health District,Total Cases,Hospitalizations,Deaths
0,2020-11-28,51001,Accomack,Eastern Shore,1340,107,21
1,2020-11-28,51003,Albemarle,Thomas Jefferson,1896,100,27
2,2020-11-28,51005,Alleghany,Alleghany,316,19,7
3,2020-11-28,51007,Amelia,Piedmont,210,21,6
4,2020-11-28,51009,Amherst,Central Virginia,810,31,6
...,...,...,...,...,...,...,...
51865,2021-04-10,51800,Suffolk,Western Tidewater,7568,426,180
51866,2021-04-10,51810,Virginia Beach,Virginia Beach,33960,1483,369
51867,2021-04-10,51820,Waynesboro,Central Shenandoah,2280,71,35
51868,2021-04-10,51830,Williamsburg,Peninsula,727,24,11
51869,2021-04-10,51840,Winchester,Lord Fairfax,2726,109,41

In [141]:
covid_counts = covid1.groupby(['Report Date']).sum().sort_values('Report Date',ascending=False)
covid_counts=covid_counts.reset_index()
covid_counts

    Report Date  Total Cases  Hospitalizations  Deaths
0    2021-04-10       634325             27161   10458
1    2021-04-09       632625             27099   10451
2    2021-04-08       631083             27012   10436
3    2021-04-07       629155             26911   10415
4    2021-04-06       627605             26815   10401
..          ...          ...               ...     ...
385  2020-03-21          152                25       2
386  2020-03-20          114                20       2
387  2020-03-19           94                18       2
388  2020-03-18           77                17       2
389  2020-03-17           67                18       2

[390 rows x 4 columns]

In [142]:
covid_counts["Report Date"]= pd.to_datetime(covid_counts['Report Date'])
covid_counts

    Report Date  Total Cases  Hospitalizations  Deaths
0    2021-04-10       634325             27161   10458
1    2021-04-09       632625             27099   10451
2    2021-04-08       631083             27012   10436
3    2021-04-07       629155             26911   10415
4    2021-04-06       627605             26815   10401
..          ...          ...               ...     ...
385  2020-03-21          152                25       2
386  2020-03-20          114                20       2
387  2020-03-19           94                18       2
388  2020-03-18           77                17       2
389  2020-03-17           67                18       2

[390 rows x 4 columns]

In [146]:
# Converting 'date' to merge with Covid 'Report Date'
df3["date"]= pd.to_datetime(df3["date"])
df3

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,...,id,start_lat,start_lng,end_lat,end_lng,state,county,city,locale,date
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,...,1,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington,2019-10-01
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,...,2,38.887374,-77.001958,38.887374,-77.001958,District of Columbia,,Washington,Washington,2019-10-01
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,...,3,38.912097,-77.038689,38.912097,-77.038689,District of Columbia,,Washington,Washington,2019-10-01
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,...,4,38.938741,-77.087181,38.938741,-77.087181,District of Columbia,,Washington,Washington,2019-10-01
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,...,5,38.908644,-77.012366,38.908644,-77.012366,District of Columbia,,Washington,Washington,2019-10-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,...,158126,38.905731,-77.022264,38.905731,-77.022264,District of Columbia,,Washington,Washington,2019-02-28
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,...,158127,38.908596,-77.032308,38.908596,-77.032308,District of Columbia,,Washington,Washington,2019-02-28
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,...,158128,38.917807,-77.032079,38.917807,-77.032079,District of Columbia,,Washington,Washington,2019-02-28
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,...,158129,38.884090,-76.995180,38.884090,-76.995180,District of Columbia,,Washington,Washington,2019-02-28
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,...,158130,38.906599,-77.051494,38.906599,-77.051494,District of Columbia,,Washington,Washington,2019-02-28

In [147]:
df4 = pd.merge(left=df3, right=covid_counts, how='left', 
               left_on='date', right_on='Report Date')

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,...,end_lng,state,county,city,locale,date,Report Date,Total Cases,Hospitalizations,Deaths
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,...,-77.038689,District of Columbia,,Washington,Washington,2019-10-01,NaT,NaN,NaN,NaN
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,...,-77.001958,District of Columbia,,Washington,Washington,2019-10-01,NaT,NaN,NaN,NaN
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,...,-77.038689,District of Columbia,,Washington,Washington,2019-10-01,NaT,NaN,NaN,NaN
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,...,-77.087181,District of Columbia,,Washington,Washington,2019-10-01,NaT,NaN,NaN,NaN
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,...,-77.012366,District of Columbia,,Washington,Washington,2019-10-01,NaT,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,...,-77.022264,District of Columbia,,Washington,Washington,2019-02-28,NaT,NaN,NaN,NaN
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,...,-77.032308,District of Columbia,,Washington,Washington,2019-02-28,NaT,NaN,NaN,NaN
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,...,-77.032079,District of Columbia,,Washington,Washington,2019-02-28,NaT,NaN,NaN,NaN
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,...,-76.995180,District of Columbia,,Washington,Washington,2019-02-28,NaT,NaN,NaN,NaN
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,...,-77.051494,District of Columbia,,Washington,Washington,2019-02-28,NaT,NaN,NaN,NaN

In [149]:
df4['Total Cases'] = df4['Total Cases'].replace(np.nan, 0)
df4['Hospitalizations'] = df4['Hospitalizations'].replace(np.nan, 0)
df4['Deaths'] = df4['Deaths'].replace(np.nan, 0)
df4

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,...,end_lng,state,county,city,locale,date,Report Date,Total Cases,Hospitalizations,Deaths
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,...,-77.038689,District of Columbia,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,...,-77.001958,District of Columbia,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,...,-77.038689,District of Columbia,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,...,-77.087181,District of Columbia,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,...,-77.012366,District of Columbia,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,...,-77.022264,District of Columbia,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,...,-77.032308,District of Columbia,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,...,-77.032079,District of Columbia,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,...,-76.995180,District of Columbia,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,...,-77.051494,District of Columbia,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0

In [151]:
df4.sort_values(by='date')

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,...,end_lng,state,county,city,locale,date,Report Date,Total Cases,Hospitalizations,Deaths
5581774,531.0,2019-02-01 18:45:35,2019-02-01 18:54:27,31265.0,5th St & Massachusetts Ave NW,31519.0,1st & O St NW,W20094,member,2019-02,...,-77.018678,District of Columbia,,Washington,Washington,2019-02-01,NaT,0.0,0.0,0.0
5581327,542.0,2019-02-01 17:05:10,2019-02-01 17:14:12,31201.0,15th & P St NW,31117.0,15th & Euclid St NW,W24170,member,2019-02,...,-77.034412,District of Columbia,,Washington,Washington,2019-02-01,NaT,0.0,0.0,0.0
5581328,139.0,2019-02-01 17:05:27,2019-02-01 17:07:46,31257.0,22nd & I St NW / Foggy Bottom,31212.0,21st & M St NW,W23313,member,2019-02,...,-77.048895,District of Columbia,,Washington,Washington,2019-02-01,NaT,0.0,0.0,0.0
5581329,697.0,2019-02-01 17:05:44,2019-02-01 17:17:22,31287.0,10th St & L'Enfant Plaza SW,31624.0,North Capitol St & F St NW,W00485,member,2019-02,...,-77.026002,District of Columbia,,Washington,Washington,2019-02-01,NaT,0.0,0.0,0.0
5581330,450.0,2019-02-01 17:05:45,2019-02-01 17:13:15,31252.0,21st St & Pennsylvania Ave NW,31298.0,15th & M St NW,W00245,member,2019-02,...,-77.046578,District of Columbia,,Washington,Washington,2019-02-01,NaT,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4980848,NaN,2021-03-31 09:40:34,2021-03-31 10:02:49,31666.0,4th St & G St SW,31127.0,22nd & H St NW,AE8DCA00BE5A93F7,member,2021-03,...,-77.017656,District of Columbia,,Washington,Washington,2021-03-31,2021-03-31,618976.0,26455.0,10252.0
5097245,NaN,2021-03-31 12:26:16,2021-03-31 12:31:28,31248.0,Smithsonian-National Mall / Jefferson Dr & 12t...,31218.0,L'Enfant Plaza / 7th & C St SW,746307562A96591A,member,2021-03,...,-77.028670,District of Columbia,,Washington,Washington,2021-03-31,2021-03-31,618976.0,26455.0,10252.0
4980847,NaN,2021-03-31 08:23:01,2021-03-31 08:26:41,31128.0,23rd & M St NW,31127.0,22nd & H St NW,6AC0B413F771BCDD,member,2021-03,...,-77.050264,District of Columbia,,Washington,Washington,2021-03-31,2021-03-31,618976.0,26455.0,10252.0
4991152,NaN,2021-03-31 19:42:47,2021-03-31 20:35:30,31271.0,Constitution Ave & 2nd St NW/DOL,31638.0,1st & H St NW,7D55AC5D86E9625D,member,2021-03,...,-77.013916,District of Columbia,,Washington,Washington,2021-03-31,2021-03-31,618976.0,26455.0,10252.0
5081085,NaN,2021-03-31 08:01:54,2021-03-31 08:08:23,31132.0,13th & U St NW,31214.0,17th & Corcoran St NW,87CF8088469C643F,member,2021-03,...,-77.029637,District of Columbia,,Washington,Washington,2021-03-31,2021-03-31,618976.0,26455.0,10252.0

In [169]:
# Calculating duration to fill out missing values and converting into seconds
df4["started_at"]=pd.to_datetime(df4["started_at"])
df4["ended_at"]=pd.to_datetime(df4["ended_at"])
df4["new_duration"] = df4["ended_at"] - df4["started_at"]
df4['new_duration(min)'] = df4['new_duration'].dt.total_seconds()
df4

,Duration,started_at,ended_at,start_station_id,start_station_name,end_station_id,end_station_name,ride_id,member_casual,fileid,...,county,city,locale,date,Report Date,Total Cases,Hospitalizations,Deaths,new_duration,new_duration(sec)
0,429.0,2019-10-01 00:01:59,2019-10-01 00:09:08,31214.0,17th & Corcoran St NW,31203.0,14th & Rhode Island Ave NW,W23731,member,2019-10,...,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0,0 days 00:07:09,429.0
1,1935.0,2019-10-01 00:03:07,2019-10-01 00:35:23,31269.0,3rd St & Pennsylvania Ave SE,31269.0,3rd St & Pennsylvania Ave SE,W22377,member,2019-10,...,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0,0 days 00:32:16,1936.0
2,563.0,2019-10-01 00:03:51,2019-10-01 00:13:14,31214.0,17th & Corcoran St NW,31251.0,12th & L St NW,W23473,member,2019-10,...,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0,0 days 00:09:23,563.0
3,625.0,2019-10-01 00:05:34,2019-10-01 00:15:59,31301.0,Ward Circle / American University,31317.0,Wisconsin Ave & Ingomar St NW,W21371,member,2019-10,...,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0,0 days 00:10:25,625.0
4,312.0,2019-10-01 00:05:47,2019-10-01 00:10:59,31519.0,1st & O St NW,31109.0,7th & T St NW,W23666,member,2019-10,...,,Washington,Washington,2019-10-01,NaT,0.0,0.0,0.0,0 days 00:05:12,312.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5737813,886.0,2019-02-28 23:55:21,2019-03-01 00:10:08,31223.0,Convention Center / 7th & M St NW,31612.0,D St & Maryland Ave NE,W23129,member,2019-02,...,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0,0 days 00:14:47,887.0
5737814,404.0,2019-02-28 23:57:03,2019-03-01 00:03:47,31203.0,14th & Rhode Island Ave NW,31223.0,Convention Center / 7th & M St NW,W00316,member,2019-02,...,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0,0 days 00:06:44,404.0
5737815,972.0,2019-02-28 23:57:03,2019-03-01 00:13:16,31101.0,14th & V St NW,31600.0,5th & K St NW,W21796,member,2019-02,...,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0,0 days 00:16:13,973.0
5737816,925.0,2019-02-28 23:57:32,2019-03-01 00:12:58,31613.0,Eastern Market Metro / Pennsylvania Ave & 7th ...,31642.0,New Jersey Ave & L St NW,W23576,member,2019-02,...,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0,0 days 00:15:26,926.0
5737817,773.0,2019-02-28 23:59:15,2019-03-01 00:12:08,31255.0,24th & N St NW,31233.0,17th & K St NW / Farragut Square,W22068,member,2019-02,...,,Washington,Washington,2019-02-28,NaT,0.0,0.0,0.0,0 days 00:12:53,773.0

In [170]:
#df4.to_csv(r'/Users/jennyjang/Desktop/CS Project/datasets/cleaned_final_v2.csv')

In [171]:
df4.columns

Index(['Duration', 'started_at', 'ended_at', 'start_station_id',
       'start_station_name', 'end_station_id', 'end_station_name', 'ride_id',
       'member_casual', 'fileid', 'rideable_type', 'id', 'start_lat',
       'start_lng', 'end_lat', 'end_lng', 'state', 'county', 'city', 'locale',
       'date', 'Report Date', 'Total Cases', 'Hospitalizations', 'Deaths',
       'new_duration', 'new_duration(sec)'],
      dtype='object')

NameError: name 'df4' is not defined